### ISSUE TITLE
Installing the Drupal module blocked access to the admin panel

### ISSUE THREAD

**Issue by Lucas-C** [nodespark/elasticsearch_connector#1]
Hello,

I actually solved this issue, but thought it'd be valuable to share my experience here.

The initial symptoms were the following:
- I installed the module from a file (`elasticsearch_connector-7.x-1.x-dev.tar.gz`) through the web interface at `/?q=admin/modules/install`
- immediately I was no more able to access any page under `/?q=admin`, but could still access the Drupal website
- removing `sites/all/elasticsearch_connector` restored a normal situation

Then I spotted an error message in my Apache log:

    [Tue Jun 09 10:00:38.143372 2015] [mpm_winnt:notice] [pid 10476:tid 460] AH00428: Parent: child process 11216 exited with status 3221225725 -- Restarting.

An found the solution on [StackOverflow](http://stackoverflow.com/a/23138604) :

    <IfModule mpm_winnt_module>
        ThreadStackSize 8888888
    </IfModule>

I am now able to install the elasticsearch_connector module without trouble.

**Comment by nignatov** [comment]
@Lucas-C,

Thank you for sharing this.
