### ISSUE TITLE
Guzzle Error

### ISSUE THREAD

**Issue by bogdan24pop** [nodespark/elasticsearch_connector#11]
Fatal error: Class 'GuzzleHttp\Ring\Client\CurlHandler' not found in var/www/****/modules/contrib/elasticsearch_connector/src/ElasticSearch/ClientManager.php on line 55

I get this fatal error. Guzzle is properly installed. I got Guzzle classes in autoload_classmap.php. I have tried to require autoload.php into ClientManager.php. Do you have any ideas? This happens when I try to add a cluster.  "elasticsearch/elasticsearch": "~2.0" library installed.

**Comment by Mgibs** [comment]
Did you check your guzzle version ? 
Are you using Drupal 8 ?

**Comment by bogdan24pop** [comment]
It's Drupal 8. Guzzle v6. I solve it by adding
require_once './modules/contrib/elasticsearch_connector/vendor/autoload.php';

**Comment by nignatov** [comment]
Hmmm, actually you should not have elasticsearch_connector/vendor/autoload.php file. It seems you didn't install the library correctly, it seems you have run composer install into the elasticsearch_connector module itself. 
In D8, when you are dealing with composer you should consider modifying the core composer.json file or use the Composer Manager module that will do the same but in a transparent way. 

To do it manually, you can edit the core composer.json file and include the elasticsearch_connector composer.json file e.g.

.......
"merge-plugin": {
      "include": [
        "core/composer.json",
        "modules/elasticsearch_connector/composer.json"
      ],
......

where "modules/elasticsearch_connector/composer.json" is the path to the composer.json file.

**Comment by bogdan24pop** [comment]
Got it. Thanks
